eesast/api

docs/swagger.yaml, src/models/contest.ts, src/routes/teams.ts
=> Add api for contest availability

docs/swagger.yaml, src/app.ts, src/models/enrollment.ts, src/routes/enrollments.ts
=> Add enrollments endpoint

docs/swagger.yaml, package.json, src/routes/announcements.ts, src/routes/static.ts, yarn.lock
文件名使用原始文件名的utf-8编码，若已有文件则后接uuid
将公告改为按更新时间排序
=> Use original filename in static endpoint

src/app.ts, src/routes/static.ts
=> Fix encode bug

src/routes/teams.ts
修正判断req.query.self时的类型错误，现在前端获取的selfTeam应该正常无误
=> :bug: Fix type error when judging req.query.self

src/routes/users.ts
email是nullable的，email=undefined也会返回一个用户
=> Fix login findOne with undefined email

package.json, src/routes/static.ts, test/static.ts, yarn.lock
[https://github.com/isaacs/node-mkdirp/issues/3](https://github.com/isaacs/node-mkdirp/issues/3)
=> Fix bug caused by mkdirp major update

src/app.ts, src/routes/teams.ts
[https://github.com/cdimascio/express-openapi-validator#upgrading-from-v2xx](https://github.com/cdimascio/express-openapi-validator#upgrading-from-v2xx)
=> Fix asynchronous express-openapi-validator 3

package.json, test/babel-register.js, tsconfig.json, yarn.lock
=> Include test in eslint

docs/swagger.yaml, src/routes/users.ts
加入/username/:id，即通过/v1/users/username/:id获取对应id的username，不需要认证
需求：Weekly文章阅读时作者用户名的获取
=> :sparkles: Add /username/:id to get username

docs/swagger.yaml, src/app.ts, src/middlewares/authenticate.ts, src/models/track.ts, src/routes/tracks.ts, test/setup.ts, test/tracks.ts, test/users.ts, test/variables.ts
=> Add track endpoint

docs/swagger.yaml, src/models/track.ts, src/routes/tracks.ts, test/tracks.ts
=> add support for preliminary contest

src/routes/contests.ts, src/routes/rooms.ts, src/routes/teams.ts, src/routes/tracks.ts
Fix mongoose type and remove checkToken from teams endpoint.
=> Fix mongoose type

src/routes/rooms.ts
注意：dockerode的type定义分中有一处错误，将`IPv4Address`写为`Ipv4Address`
=> Create agent when starting room

docs/swagger.yaml, scripts/update_score.py, src/middlewares/checkServer.ts, src/routes/codes.ts, src/routes/rooms.ts, src/routes/teams.ts
- 添加用于根据比赛结果更改分数的`/teams/scores`和对应的文档
- 添加用于计算分数的py脚本至`scripts`文件夹下
- 编译容器启动前创建路径时指定权限为775
- 获取server在指定网络上IP处的typo使用`(containerInfo as any)`解决
=> Add /teams/scores to update scores

src/routes/codes.ts, src/routes/rooms.ts
似乎现在回两次更改数据库中的Code，导致没有正确更改。改为else试着解决此问题
=> Upload compile info

src/routes/codes.ts, src/routes/rooms.ts, src/routes/teams.ts
- 修改分数计算时未使用promise确保结果的问题
- 修改房间创建时未向agent传入token的问题
=> Room & Team bug fix

src/routes/teams.ts
修改回放文件的存储方式
添加分数到log中以便查看是否正常返回分数
=> Try to save playback correctly

docs/swagger.yaml, src/routes/teams.ts
=> update room status in /teams/scores & allow get teams sort by score

scripts/auto_remove_container_network, src/routes/room.ts
1. 需要等到前端做好再部署
2. team_seq只能是 0 或 1
=> 增加指定 team 顺序入队

src/helpers/docker_queue.ts
use setTimeout function to set a timelimit for docker container.
=> add docker stop time

src/helpers/docker_queue.ts
use "HostConfig: Memory" to set limit, instead of "Cmd"
=> memory limit

src/helpers/docker_queue.ts
=> set memory swap limit

src/routes/static.ts
=> refactor(static): 添加一个根路径鉴权(只判断是不是管理员)

src/routes/code.ts, src/routes/static.ts
code.ts 删掉了一些冗余的try catch
static.ts 与前端做了相应的调整
=> fix&refact: code download & COS routes

src/routes/code.ts
player_num = 5
减少了重复的代码
用 await/async 语法简化了code 下载部分的 Promise 结构
=> simplify code.ts

src/helpers/htmlTemplates.ts, src/index.ts, src/middlewares/authenticate.ts, src/routes/users_mongo.ts
修改users.ts，完成 email 的 login,verify,register 操作
=> feat(users): finish login, verify, register

package.json, src/helpers/short_message.ts, src/routes/user.ts, yarn.lock
use UniSMS to send short message verification code.
=> feat(user): add SMS for phone verify

src/helpers/docker_queue.ts, src/helpers/utils.ts, src/routes/code.ts, src/routes/room.ts
完成了 code.ts & room.ts 的测试.
Postman 测试流程在这里：[THUAI_TEST](https://documenter.getpostman.com/view/21990568/2sA2xiWBev)
修改了一些 graphql：$user_uuid: String -> uuid!
=> feat(code & room): test docker thuai6_cpp & thuai6_run

src/helpers/docker_queue.ts, src/helpers/hasura.ts, src/routes/arena.ts, src/routes/competition.ts
Separate source path for different teams
Add support for symmetrical competition
Add comment for hasura api
=> Fix some bugs

package.json, yarn.lock
=> revert: node-fetch revert to v2

renovate.json
被 renovate 搞崩了，大概是这条 [commit](https://github.com/eesast/api/commit/7e4998deaf0ccb150f7cb58000cb2df35c5d63f2)
先停了再说
=> fix: roll off and disable renovate

src/helpers/validate.ts, src/middlewares/authenticate.ts, src/routes/user.ts
=> feat: add register with role selection

src/hasura/contest.ts, src/routes/arena.ts, src/routes/competition.ts
- hasura/contest.ts: add update_room_team_player_roles for player_roles update.
- routes/arena.ts: modify finish route, add COS upload extra and player_roles update.
- routes/competition.ts: modify finish-one route, add COS upload extra and player_roles update.
=> modify route for extra and player_roles
